src/estacionamento/urls.py
from django.urls import path
from . import views

app_name = 'estacionamento'
urlpatterns = [
    path('entrance/', views.car_entrance, name = "entrada"),
    path('exit/', views.car_exit, name = "saida"),
    path('',views.car_menu, name='menu'),
    path('result/detail/<int:my_id>',views.car_detail_view, name= 'car_detail'),
    path('result/<int:my_id>', views.car_redirect, name = 'redirect')
]

src/trydjango/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home
from products.views import product_dynamic_view , product_create_view, top_products, loja_view
from JogoMemoria.views import memoria_view
from estacionamento.views import *
urlpatterns = [
    path('', home ,name = "home"),
    path('admin/', admin.site.urls),

    path('loja/product/detail/<int:my_id>',product_dynamic_view),
    path('loja/menu', loja_view,name = 'menu'),
    path('loja/product/create/', product_create_view, name = 'Create'),
    path('loja/product/top_products/',top_products, name = 'Create'),
    path('memoria/',memoria_view, name = 'jogo'),
    path('estacionamento/', include('estacionamento.urls')),

]

src/estacionamento/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
#    id          =  models.AutoField()
    modelo      =  models.CharField(max_length = 20)
    placa       =  models.CharField(max_length = 7,unique= True)
    in_date     = models.DateTimeField(auto_now = True, null = True)
    out_date    = models.DateTimeField(null = True, default = None)
    presente    = models.BooleanField(default = True)

class Caixa(models.Model):
    cash        = models.DecimalField(max_digits = 4,decimal_places = 2)

src/estacionamento/forms.py
from django import forms
from django.forms import ModelForm
from .models import Car

class CarForms(ModelForm):
    class Meta:
        model = Car
        fields = [
        'modelo',
        'placa',

        ]

class CarIdForm(ModelForm):
    class Meta:
        model = Car
        fields =[
        'id'
        ]
#
# class CarExit(ModelForm):
#     class Meta;
#     model = Car
#     fields= [
#
#     ]

src/estacionamento/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect,Http404, HttpResponse
from .models import Car
from .forms import CarForms
from django.urls import reverse
from django.template import loader

# Create your views here.
def car_entrance(request):
    form = CarForms(request.POST or None)
    if form.is_valid():
        form.save()

    context = {
        'form':form
    }

    return render(request , "carros/Entrada.html",context)

def car_exit(request):
    #HttpResponseRedirect(Car,My_id)
    try:
        car = Car.objects.all()
        print(car)
    except :
        raise Http404("O carro não existe")
    context = {
        'car': car,
    }
    return render(request,"carros/saida.html",{})

def car_menu(request):
    return render(request, "menu.html")


def car_detail_view(request, my_id):
    obj = get_object_or_404(Car, id = my_id)
    context = {
    'object' : obj,
    }
    return render(request,"carros/cardetail.html", context)

def car_redirect(request, my_id):

    print(request.POST)

    number = request.POST['carid']
    try:
            if Car.objects.get(id = number).DoesNotExist:
                return HttpResponseRedirect(reverse('estacionamento:car_detail', args = (number,)))
    except:
        return HttpResponse("car does not exist")

src/estacionamento/templates/carros/Entrada.html
{%extends 'menu.html'%}

{%block content%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Entrada</title>
    <style media="screen">

input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;

}
</style>

  </head>
  <body>
    <h1>Entrada com um novo carro</h1>
    <form class="" action="." method="POST">{% csrf_token%}
      {{form.as_p}}
      <input type="submit" name="" value="Save">

    </form>
  </body>
</html>
{%endblock%}

src/estacionamento/templates/carros/cardetail.html
{%extends 'menu.html'%}


{%block content%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>MODELO</h1>
    <h3>{{object.modelo}}</h3>
    <h2>PLACA:</h2>
    <h3>{{object.placa}}</h3>
    <h2>Horario de entrada</h2>
    <h3>{{object.in_date}}</h3>
  </body>
</html>
{%endblock%}

src/estacionamento/templates/carros/detail.html
{%extends 'base.html'%}


{%block content%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Item nuevo</h1>
    <h1>{{object.title}}</h1>
    <h2>descrição:</h2>
    <p>{%if object.description%}{{object.description}}{%else%}em breve mais desciçaõ{%endif%}</p>
    <h2>Price: {{object.price}} </h2>
    <h3>Disponibilidade:</h3>
    <p>{%if object.stock == 0%}fora de estoque{%else%}Em estoque{%endif%}</p>
  </body>
</html>
{%endblock%}

src/estacionamento/templates/carros/saida.html
{%extends 'menu.html'%}

{%block content%}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Entrada</title>
<style media="screen">

    input[type=text], select {
      width: 100%;
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
    }

    input[type=submit] {
      width: 100%;
      background-color: #4CAF50;
      color: white;
      padding: 14px 20px;
      margin: 8px 0;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }

    input[type=submit]:hover {
      background-color: #45a049;
    }

    div {
      border-radius: 5px;
      background-color: #f2f2f2;

    }
  </style>
  </head>
  <body>

<h1>saida de carros</h1>
<form class="" action="{%url 'estacionamento:redirect' 0%}" method="POST">{%csrf_token%}

  <input type="integer" name="carid">
  <input type="submit" name="" value="saida">

</form>
  </body>
</html>

{%endblock%}